        !COMPILER-GENERATED INTERFACE MODULE: Sun Apr 11 06:15:18 2021
        ! This source file is for reference only and may not completely
        ! represent the generated interface used by the compiler.
        MODULE GENIE_RESTARTS__genmod
          INTERFACE 
            SUBROUTINE GENIE_RESTARTS(KOVERALL,LRESTART_GENIE,ALON1_ATM,&
     &ALAT1_ATM,OCEAN_SENSIBLE_ATM,OCEAN_LATENT_ATM,OCEAN_STRESSX_ATM,  &
     &OCEAN_STRESSY_ATM,OCEAN_SENSIBLEINST_ATM,OCEAN_STRESSXINST_ATM,   &
     &OCEAN_STRESSYINST_ATM,OCEAN_EVAPINST_ATM,OCEAN_LATENTINST_ATM,    &
     &OCEAN_TSTARINST_ATM,OCEAN_ROUGH_ATM,OCEAN_QSTAR_ATM,OCEAN_SALB_ATM&
     &,TSTAR_ATM,ALBEDO_ATM,RESTART_TYPE)
              INTEGER(KIND=4) :: KOVERALL
              LOGICAL(KIND=4) :: LRESTART_GENIE
              REAL(KIND=8) :: ALON1_ATM(64)
              REAL(KIND=8) :: ALAT1_ATM(32)
              REAL(KIND=8) :: OCEAN_SENSIBLE_ATM(64,32)
              REAL(KIND=8) :: OCEAN_LATENT_ATM(64,32)
              REAL(KIND=8) :: OCEAN_STRESSX_ATM(64,32)
              REAL(KIND=8) :: OCEAN_STRESSY_ATM(64,32)
              REAL(KIND=8) :: OCEAN_SENSIBLEINST_ATM(64,32)
              REAL(KIND=8) :: OCEAN_STRESSXINST_ATM(64,32)
              REAL(KIND=8) :: OCEAN_STRESSYINST_ATM(64,32)
              REAL(KIND=8) :: OCEAN_EVAPINST_ATM(64,32)
              REAL(KIND=8) :: OCEAN_LATENTINST_ATM(64,32)
              REAL(KIND=8) :: OCEAN_TSTARINST_ATM(64,32)
              REAL(KIND=8) :: OCEAN_ROUGH_ATM(64,32)
              REAL(KIND=8) :: OCEAN_QSTAR_ATM(64,32)
              REAL(KIND=8) :: OCEAN_SALB_ATM(64,32)
              REAL(KIND=8) :: TSTAR_ATM(64,32)
              REAL(KIND=8) :: ALBEDO_ATM(64,32)
              INTEGER(KIND=4) :: RESTART_TYPE
            END SUBROUTINE GENIE_RESTARTS
          END INTERFACE 
        END MODULE GENIE_RESTARTS__genmod
