
      SUBROUTINE SAVEPS(FNAME,NOUT)
      include 'mappings.inc'
C
      INTEGER NOUT
      INTEGER I1
      INTEGER I2
      INTEGER I3
      INTEGER I4
C
      CHARACTER FNAME*(*)
      LOGICAL LEXIST
1000  FORMAT(6I4)
1001  FORMAT(20I4)
1002  FORMAT(11F7.2)

      ISAVE=2
      LSAVE=.TRUE.
      NCHAN=NOUT
      FILENAME=FNAME
C
C
      INQUIRE(FILE=FNAME,EXIST=LEXIST)
      IF(LEXIST)THEN
       OPEN(UNIT=NCHAN,FILE=FNAME,FORM='FORMATTED',STATUS='OLD')
       CLOSE(UNIT=NCHAN,STATUS='DELETE')
      ENDIF
C
      OPEN(UNIT=NCHAN,FILE=FNAME,STATUS='NEW',FORM='FORMATTED')
C
      I1=1
      I2=IEGA
      I3=IMON
      I4=0
      WRITE(NCHAN,1000)I1,I2,I3,I4,I4,I4
      WRITE(NCHAN,1002)XSPACE1,XSPACE2,YSPACE2,YSPACE1,OBLATE
      END
