      SUBROUTINE XAXISX(XO,YO,XSTEP)
C  To draw X-AXIS through (XO,YO) with tick interval of XSTEP.
C  If XSTEP=0.0,the interval is set automatically
      INTEGER JUMP
      REAL UNITH
      REAL XRANGE
      REAL YRANGE
      REAL UH
      INTEGER NTMAG
      REAL ANMAG
      REAL ANSIZ
      REAL YFACTR
      REAL HX
      REAL XFACTR
      REAL HY
      REAL HOLD
      REAL XL
      REAL YO
      REAL XR
      REAL XSTEP
      REAL XSTEPJ
      REAL XAXINC
      INTEGER KTKX
      REAL HTICK
      REAL AXL
      REAL XO
      INTEGER I
      REAL X
      INTEGER JUMPX
      REAL YSHIFT
      INTEGER KANX
      INTEGER LAXFMT
      INTEGER LCH
      INTEGER KCH
      INTEGER ICLENG
      REAL YB
      REAL YT
      REAL XSCALE
      REAL YSCALE
      REAL PL
      REAL PR
      REAL PB
      REAL PT
      INTEGER LLBFMT
      INTEGER KANY
      INTEGER KTKY
C
      PARAMETER( JUMP =2 )
      COMMON /XMAP04/ XL,XR,YB,YT,XSCALE,YSCALE
      COMMON /XPHY01/ PL,PR,PB,PT,XRANGE,YRANGE
      COMMON /XFTR06/ XFACTR,YFACTR
      COMMON /XFMT33/ LBFMT, AXFMT
      COMMON /XFMT34/ LLBFMT,LAXFMT
      COMMON /XAXS18/ KANX,KANY, KTKX,KTKY
      CHARACTER LBFMT*50, AXFMT*10
      CHARACTER CH*20
      COMMON /XAXM35/ NTMAG, ANMAG, ANSIZ
      UNITH=SQRT( ABS(XRANGE*YRANGE))*0.01
      UH= MIN( ABS(XRANGE), ABS(YRANGE) )*0.03
      IF( NTMAG.EQ.0) ANMAG=UH
      IF( NTMAG.EQ.2) ANMAG=ANSIZ*YFACTR
      HX= ANMAG/XFACTR
      HY= ANMAG/YFACTR
      CALL XQCHMG( HOLD )
      CALL XCHMAG( ANMAG )
      CALL XPENUP( XL, YO)
      CALL XPENDN( XR, YO)
      IF( XSTEP.EQ.0.0) THEN
      XSTEPJ=XAXINC(XR-XL)
      GOTO 115
      ENDIF
      IF( KTKX.EQ.0) GOTO 110
      HTICK=UNITH    /YFACTR*KTKX
      AXL=XO+ INT((XL-XO)/XSTEP)*XSTEP
      DO 100 I=0,1000
       X=AXL+I*XSTEP
       IF ((X-XL)*(X-XR).GT.0.0) GOTO 110
       CALL XPENUP(X,YO)
       CALL XPENDN (X,YO+HTICK)
100   CONTINUE
110   JUMPX=JUMP
      IF( NINT((XR-XL)/XSTEP).GT.6  ) JUMPX=JUMP*2
      XSTEPJ=XSTEP*JUMPX
115   AXL=XO+ INT((XL-XO)/XSTEPJ)*XSTEPJ
      YSHIFT=HY*1.5*KANX
      HTICK=UNITH*1.5/YFACTR*KTKX
      DO 150 I=0,1000
       X=AXL+XSTEPJ*I
       IF ((X-XL)*(X-XR).GT.0.0) GOTO 160
       IF( AXFMT(1:LAXFMT).EQ.'*') THEN
         CALL XRCH(X, CH, LCH)
       ELSE
         DO 503 KCH=1,LAXFMT
           IF((AXFMT(KCH:KCH).EQ.'I')
     :            .or.(AXFMT(KCH:KCH).EQ.'i'))THEN
           WRITE(CH,AXFMT(1:LAXFMT)) NINT(X)
           GOTO 504
         ENDIF
 503       CONTINUE
           WRITE(CH,AXFMT(1:LAXFMT)) X
 504       LCH=ICLENG( CH )
         CALL XCHLJ( CH(1:LCH), LCH)
       ENDIF
       IF(KANX.NE.0 )   CALL XCHARC(X, YO+YSHIFT, CH(1:LCH) )
       IF(KTKX.NE.0.AND.XSTEP.EQ.0.0 .OR. KTKX.NE.0.AND.KANX.NE.0)THEN
         CALL XPENUP(X,YO)
         CALL XPENDN(X,YO+HTICK)
       ENDIF
 150  CONTINUE
 160  CONTINUE
      CALL XCHMAG( HOLD )
      RETURN
      END
