      REAL FUNCTION XAXINC(X)
C TO SET ANNOTATION INCREMENT (ANNOTATIONS >=4 AND =<16 FOR FOLD=1.0)
C
      INTEGER IPOWER
      REAL X
      REAL D
      REAL FOLD
C
      IPOWER= INT(  LOG10(X) )
      D= INT(X/10**IPOWER)
      FOLD=1.0
      IF(D.GE.1.0.AND.D.LT.3.0) THEN
      XAXINC=2.0*10.0**(IPOWER-1)*FOLD
      ELSEIF(D.GE.3.0.AND.D.LT.7.0) THEN
      XAXINC=5.0*10.0**(IPOWER-1)*FOLD
      ELSEIF(D.GE.7.0.AND.D.LT.10.) THEN
      XAXINC=1.0*10.0** IPOWER*FOLD
      ENDIF
      IF(XAXINC .EQ.0.0) XAXINC=X*0.1
      RETURN
      END
