      SUBROUTINE XCFONT( IFONT )
C
      INTEGER KF
      INTEGER KFONT
      INTEGER IFONT
      INTEGER NFONT
      REAL HCTR
      REAL SCTR
      REAL CRATIO
      INTEGER NUNDLN
C
      COMMON /XCHA20/ HCTR,SCTR,CRATIO, KFONT,NUNDLN
      COMMON /XCHR31/ CHDATA
      COMMON /XCHR32/ ICDATA
      CHARACTER CHDATA(127)*300
      INTEGER ICDATA (0:150 , 32:127)
      KF=KFONT
      KFONT=IFONT
      IF ((KFONT .LT. 1) .OR. (KFONT .GT. 4)) THEN
       PRINT*,'Error in subroutine XCFONT, KFONT= ',KFONT
       STOP
      ENDIF
      IF( KF.EQ. KFONT) RETURN
      GOTO ( 501, 502, 503, 504 ) KFONT
 501  CALL XCSETB(CHDATA)
      GOTO 505
 502  CALL XCSETC(CHDATA)
      GOTO 505
 503  CALL XCSETA(CHDATA)
      GOTO 505
 504  CALL XCSETD(CHDATA)
 505  CONTINUE
      RETURN
      ENTRY XQCFNT ( NFONT )
      NFONT=KFONT
      RETURN
      END
