      SUBROUTINE XCHLIN( N )
C
      INTEGER NUNDLN
      INTEGER N
      INTEGER NN
      REAL HCTR
      REAL SCTR
      REAL CRATIO
      INTEGER KFONT
C
      COMMON /XCHA20/ HCTR,SCTR,CRATIO, KFONT,NUNDLN
      NUNDLN=N
      RETURN
      ENTRY XQCHLN ( NN )
      NN=NUNDLN
      RETURN
      END
