      SUBROUTINE XCHMAG(H)
C
      REAL HCTR
      REAL H
      REAL SCTR
      REAL YFACTR
      REAL HH
      REAL HC
      REAL CS1
      REAL CRATIO
      INTEGER KFONT
      INTEGER NUNDLN
      REAL XFACTR
C
      COMMON /XCHA20/ HCTR,SCTR,CRATIO, KFONT,NUNDLN
      COMMON /XFTR06/ XFACTR,YFACTR
      HCTR=ABS(H)
      SCTR=HCTR/YFACTR
      RETURN
      ENTRY XQCHMG(HH )
      HH=HCTR
      RETURN
      ENTRY XCHSIZ( HC )
      SCTR= HC
      HCTR= SCTR*YFACTR
      RETURN
      ENTRY XQCHSZ( CS1 )
      CS1= HCTR/YFACTR
      RETURN
      END
