      SUBROUTINE XCHOBL( CTROBL )
C
      REAL CRATIO
      REAL CTROBL
      REAL COBL
      REAL HCTR
      REAL SCTR
      INTEGER KFONT
      INTEGER NUNDLN
C
      COMMON /XCHA20/  HCTR,SCTR,CRATIO, KFONT,NUNDLN
      CRATIO= CTROBL
      RETURN
      ENTRY XQCHOB( COBL )
      COBL=CRATIO
      RETURN
      END
