      SUBROUTINE  XCHRST(X2,Y2)
C Perform rotation around picture reference point (XMREF,YMREF)
C
      REAL XSYMAN
      REAL X1
      REAL X2
      REAL XCHPO
      REAL Y1
      REAL Y2
      REAL YCHPO
      REAL CHCOS
      REAL CHSIN
      REAL CHANG
      REAL RADANG
      REAL XANGLE
      REAL CRANG
      REAL DRANG
      REAL SRANG
      INTEGER KSR
      REAL XA
      REAL SYMANG
      REAL XCHPEN
      REAL YCHPEN
      REAL XCHMO
      REAL YCHMO
      REAL YA
      REAL SINDRA
      REAL COSDRA
      REAL SINMRA
      REAL COSMRA
      REAL SINSRA
      REAL COSSRA
      REAL SINXA
      REAL COSXA
      REAL SINYA
      REAL COSYA
C
      COMMON /XCHP21/ XCHPEN, YCHPEN ,XCHMO,YCHMO,XCHPO,YCHPO
      COMMON /XAGS09/ DRANG,CRANG,XANGLE,XSYMAN,SRANG,KSR,XA,YA
      COMMON /XSCS10/ SINDRA,COSDRA,SINMRA,COSMRA,SINSRA,COSSRA
     :              ,SINXA,COSXA,SINYA,COSYA ,CHSIN,CHCOS
      IF( XSYMAN.EQ.0.0) RETURN
      X1=X2-XCHPO
      Y1=Y2-YCHPO
      X2=X1*CHCOS-Y1*CHSIN +XCHPO
      Y2=X1*CHSIN+Y1*CHCOS +YCHPO
      RETURN
      ENTRY XCHORI(CHANG)
      XSYMAN=CHANG
      IF( CHANG.EQ.0) GOTO 3
      RADANG= ATAN(1.)/45.0*XSYMAN
      CHSIN= SIN( RADANG)
      CHCOS= COS( RADANG)
      XANGLE=CRANG+DRANG+(90-SRANG)*KSR+XA
      RETURN
 3    CHSIN= 0.0
      CHCOS= 1.0
      RETURN
      ENTRY XQCHOR(SYMANG)
      SYMANG=XSYMAN
      RETURN
      END
