      SUBROUTINE XCTRAN(X,Y)
C
      REAL X1
      REAL X
      REAL Y1
      REAL Y
      INTEGER KPROJC
      REAL XLTRNX
      REAL XLTRNY
      REAL DXMOP
      REAL DYMOP
      REAL DXPO
      REAL DYPO
C
      COMMON /XPHO03/ DXPO,DYPO
      COMMON /XMAO05/ DXMOP,DYMOP
      COMMON /XPRJ26/ KPROJC
      EXTERNAL XLTRNX,XLTRNY
      X1=X
      Y1=Y
      IF(KPROJC.NE.0)  CALL XPROJC(X1,Y1)
      X1=XLTRNX(X1)
      Y1=XLTRNY(Y1)
      CALL XCHRST(X1,Y1)
C     CALL XSRSET(X1,Y1)
      CALL XOBSET(X1,Y1)
      CALL XMRSET(X1,Y1)
      X1=X1+DXMOP
      Y1=Y1+DYMOP
      CALL XDRSET(X1,Y1)
      X=X1+DXPO
      Y=Y1+DYPO
      RETURN
      END
