C
      subroutine XPPSC
      COMMON /XPVD01/ IPV,IPSC,IPSCTMP,ICOLTX(4),IPSCEXP,IMASKCOL
C
      INTEGER IPSCTMP
      INTEGER IPV
      INTEGER IPSC
      INTEGER ICOLTX
      INTEGER IPSCEXP
      INTEGER IMASKCOL
c
      IPSCTMP=1
c
      return
      end
