      SUBROUTINE XRBROK(KFULL)
C
      INTEGER IPV
      INTEGER KFULL
      REAL H
      INTEGER IF1
      REAL HF1
      INTEGER IB1
      REAL HB1
      INTEGER IF2
      REAL HF2
      INTEGER IB2
      REAL HB2
      INTEGER IPSC
      INTEGER LFULL
      INTEGER LTHICK
      REAL DTHICK
      INTEGER IPSCTMP
      INTEGER ICOLTX
      INTEGER IPSCEXP
      INTEGER IMASKCOL
C
      COMMON /XLPN13/ HF1,HB1,HF2,HB2 , LFULL ,LTHICK, DTHICK
C
      COMMON /XPVD01/ IPV,IPSC,IPSCTMP,ICOLTX(4),IPSCEXP,IMASKCOL
C
C
      IF(IPV.EQ.1)THEN
      IF(KFULL.NE.1)THEN
        H=0.001
        IF1=HF1/H
        IB1=HB1/H
        IF2=HF2/H
        IB2=HB2/H
        IF(IF1.EQ.0)IF1=1
        IF(IF2.EQ.0)IF2=1
        CALL BROKEN(IF1,IB1,IF2,IB2)
        IF(IPSC.EQ.1)CALL XBKPSC(IF1,IB1,IF2,IB2)
      ENDIF
      LFULL=KFULL
      ENDIF
      RETURN
      END
