      SUBROUTINE XVECTS(U,V,X,Y,MD,ISTEP,ND,JSTEP,XLENG1,UUNIT1)
C
      INTEGER MD
      INTEGER ND
      INTEGER M
      INTEGER N
      INTEGER IST
      INTEGER JST
      REAL XLENG
      REAL XLENG1
      REAL UUNIT
      REAL UUNIT1
      INTEGER ISTEP
      INTEGER JSTEP
      REAL XL
      REAL XR
      REAL YB
      REAL YT
      REAL X0
      REAL Y0
      INTEGER KEY
      REAL AM
C
      REAL U(MD,ND),V(MD,ND),X(MD,ND),Y(MD,ND)
C
      M =MD
      N =ND
      IST=1
      JST=1
      XLENG=XLENG1
      UUNIT=UUNIT1
      CALL XVECTU(U(IST,JST),V(IST,JST),MD,M,ISTEP,N,JSTEP,XLENG,UUNIT)
      CALL XINTSY(0.75)
      CALL XVECTR(U(IST,JST),V(IST,JST),X(IST,JST),Y(IST,JST),
     :            MD,M,ISTEP,N,JSTEP,XLENG,UUNIT)
      CALL XQMAP(XL,XR,YB,YT)
      X0=XL+(XR-XL)*0.75
      Y0=YT+(YT-YB)*0.03
      KEY=0
      AM=1.0
      IF( (M-1)/ISTEP.GT.30) AM=2.0
      CALL XVECTK(X0,Y0,XLENG*AM,UUNIT*AM, KEY)
      CALL XINTSY(0.8)
      CALL XVLMT(0.0)
      RETURN
      END
