
      SUBROUTINE ZBUF
C
      INTEGER IJOIN
      REAL XJ
      REAL YJ
      INTEGER ISPSAVE
C
      INTEGER MLIM
      PARAMETER (MLIM=8000)
      COMMON/ZEXTRA/ISPSAVE,IJOIN,XJ(MLIM),YJ(MLIM)
C
C

      IF(IJOIN.GT.1)THEN
      CALL ZDRAWC(XJ,YJ,IJOIN)
      XJ(1)=XJ(IJOIN)
      YJ(1)=YJ(IJOIN)
      IJOIN=1
      ENDIF

      RETURN
      END
