
      SUBROUTINE ZDRAWC(XJ,YJ,N)
C1.3
C
      INTEGER I
      INTEGER N
      REAL ZSTEP
      REAL ZCHAR
      REAL ANGLE
      INTEGER IFAIL
      REAL X1
      REAL Y1
      REAL ZLEN
      REAL PIH
      INTEGER LABON
      INTEGER IHTLAB
C
      INTEGER MLIM
      PARAMETER (MLIM=8000)

      INTEGER NLABEL

C
      COMMON/ZLABL/PIH,ZSTEP,ZLEN,ZCHAR,NLABEL,LABON,IHTLAB
C
C
C
      COMMON/ZLABLC/CLABEL
      CHARACTER CLABEL*20
C
C

      REAL XJ(MLIM),YJ(MLIM)

      CALL XLPNUP(XJ(1),YJ(1))
      I=1

10    CONTINUE
C
      CALL ZCLINE(XJ,YJ,N,I,ZSTEP-ZCHAR,ANGLE,1,IFAIL)
      IF(IFAIL.NE.0)RETURN
C
      X1=XJ(I)
      Y1=YJ(I)
C
      ZLEN=0.0
      CALL ZCLINE(XJ,YJ,N,I,ZCHAR,ANGLE,0,IFAIL)
      IF(IFAIL.NE.0)RETURN
C
      ANGLE=ATAN2((YJ(I)-Y1),(XJ(I)-X1))
      IF (ANGLE.GT.PIH) THEN
      ANGLE=ANGLE-2.*PIH
      ELSEIF (ANGLE.LT.-1.*PIH) THEN
      ANGLE=ANGLE+2.*PIH
      ENDIF
C
      CALL ZANGLE(ANGLE*90./PIH)
      CALL ZPLTCH(0.5*(X1+XJ(I)),0.5*(Y1+YJ(I)),CLABEL(1:NLABEL))
      CALL XLPNUP(XJ(I),YJ(I))
      ZLEN=0.0

      GO TO 10
      END
