      SUBROUTINE ZGCNTA(ZG,ALO,ALA,IWK,MD,MG,JG,CVL,NC)
C
      INTEGER MD,MG,K,NC,IWK,JG
      REAL    CV,CVL,ZG,ALO,ALA
C
      DIMENSION ZG(MD ,*),IWK(MG ,*),CVL(*),ALO(*),ALA(*)
      DO 100 K=1,NC
      CV=CVL(K)
      CALL ZGCNTR(ZG,ALO,ALA,IWK,MD,MG,JG,CV)
  100 CONTINUE
      RETURN
      END
