      SUBROUTINE ZLABON(LABEL,ILABEL,IHT)
C
      include 'zpltpm.cmn'
c      COMMON/ZPLTPM/CX,CY,ALONS,ALATS,SALATS,CALATS,RC,AMP,SNWD,CSWD
c     :,CENT,ISTL,SWITCH,XH,YH,RAD,YEND,DX,DY,YTOP,RDX,RDY,RTOP,NM,NJ
c     :,MG,JG,JG2,JG2P,MGP,MGHP,DLONG,DLAT,PI,SVAGL,CVAGL,SROT,CROT,Q
c     :,ROUSN,ROUCS,PI2,ALFA,BETA,FANST,FANED,ITRUNC,AMQ,AMR,AK,YB,AB
c     :,ICOASRD,INCCST,ICOORD,CENTY,X1LIM,X2LIM,Y1LIM,Y2LIM
c     :,Z1STEP,Z1CHAR,IZTYPE,IVECTC,ARM
C
C
      INTEGER LABON
      INTEGER IJOIN
      INTEGER IHTLAB
      INTEGER IHT
      REAL ZSTEP
      INTEGER ILABEL
      REAL ZCHAR
      REAL ZLEN
      INTEGER ISPSAVE
      REAL XJ
      REAL YJ
      REAL PIH
C
C1.3
      CHARACTER LABEL*(*)
      INTEGER NLABEL
C
      INTEGER MLIM
      PARAMETER (MLIM=8000)
      COMMON/ZEXTRA/ISPSAVE,IJOIN,XJ(MLIM),YJ(MLIM)
C
C
C
      COMMON/ZLABL/PIH,ZSTEP,ZLEN,ZCHAR,NLABEL,LABON,IHTLAB
C
C
C
      COMMON/ZLABLC/CLABEL
      CHARACTER CLABEL*20
C
C

      LABON=1
      IJOIN=1
      IHTLAB=IHT
      ZSTEP=Z1STEP

      NLABEL=ILABEL
      CLABEL(1:ILABEL)=LABEL(1:ILABEL)
      ZCHAR=(1+NLABEL)*Z1CHAR
      ZLEN=-0.5*ZCHAR+0.5*ZSTEP

      RETURN
      END
