
      SUBROUTINE ZLABOF
C
      INTEGER LABON,NLABEL,IHTLAB
      REAL    PIH,ZSTEP,ZCHAR,ZLEN
C
      COMMON/ZLABL/PIH,ZSTEP,ZLEN,ZCHAR,NLABEL,LABON,IHTLAB
C
C
      IF(LABON.EQ.1)CALL ZBUF
      LABON=0
      END
