C
      SUBROUTINE ZOUTLN
C
      INTEGER MGR,I
      REAL    FLONG
C
      include 'zpltpm.cmn'
c      COMMON/ZPLTPM/CX,CY,ALONS,ALATS,SALATS,CALATS,RC,AMP,SNWD,CSWD
c     :,CENT,ISTL,SWITCH,XH,YH,RAD,YEND,DX,DY,YTOP,RDX,RDY,RTOP,NM,NJ
c     :,MG,JG,JG2,JG2P,MGP,MGHP,DLONG,DLAT,PI,SVAGL,CVAGL,SROT,CROT,Q
c     :,ROUSN,ROUCS,PI2,ALFA,BETA,FANST,FANED,ITRUNC,AMQ,AMR,AK,YB,AB
c     :,ICOASRD,INCCST,ICOORD,CENTY,X1LIM,X2LIM,Y1LIM,Y2LIM
c     :,Z1STEP,Z1CHAR,IZTYPE,IVECTC,ARM
C
C
      IF(ISTL.EQ.0) RETURN
      GOTO (12,19,13,13,14,14,14,14,20) ISTL
C1.2
   12 CONTINUE
      CALL ZPENUP(X1LIM,Y1LIM)
      CALL ZPENDN(X2LIM,Y1LIM)
      CALL ZPENDN(X2LIM,Y2LIM)
      CALL ZPENDN(X1LIM,Y2LIM)
      CALL ZPENDN(X1LIM,Y1LIM)
      RETURN
   19 CONTINUE
      CALL ZPENUP(-XH,-YH)
      CALL ZPENDN( XH,-YH)
      CALL ZPENDN( XH, YH)
      CALL ZPENDN(-XH, YH)
      CALL ZPENDN(-XH,-YH)
      RETURN
   13 CONTINUE
      IF(BETA.EQ.PI2) GOTO 14
      MGR=(BETA*MG)/PI2
      FLONG=BETA/MGR
      CALL ZPENUP( SIN(FANST)*AMP,-COS(FANST)*RC*AMP)
      DO 15 I=1,MGR
   15 CALL ZPENDN(AMP*SIN(I*FLONG+FANST),-AMP*COS(I*FLONG+FANST)*RC)
      IF (BETA.EQ.PI) THEN
         CALL ZPENDN( SIN(FANST)*AMP,-COS(FANST)*RC*AMP)
      ELSE
         CALL ZPENDN( 0.0, 0.0)
         CALL ZPENDN( SIN(FANST)*AMP,-COS(FANST)*RC*AMP)
      END IF       
      RETURN
   14 CONTINUE
      CALL ZPENUP(AMP,0.)
      DO 18 I=1,MG
   18 CALL ZPENDN(AMP*COS(I*DLONG),AMP*SIN(I*DLONG))
      RETURN
C1.4
   20 CONTINUE
      CALL ZPENUP(2.*ARM,0.)
      DO 21 I=1,MG
   21 CALL ZPENDN(2.*ARM*COS(I*DLONG),ARM*SIN(I*DLONG))
      RETURN
      END
