      SUBROUTINE ZPENUP(XA,YA)
C
      INTEGER ISPSAVE
      INTEGER LABON
      REAL PIH
      REAL ZSTEP
      REAL ZLEN
      REAL ZCHAR
      INTEGER NLABEL
      INTEGER IHTLAB
C
      INTEGER MLIM
      PARAMETER (MLIM=8000)
      COMMON/ZEXTRA/ISPSAVE,IJOIN,XJ(MLIM),YJ(MLIM)
C
C
C
      COMMON/ZLABL/PIH,ZSTEP,ZLEN,ZCHAR,NLABEL,LABON,IHTLAB
C
C
      INTEGER IJOIN
      REAL XJ,YJ,XA,YA
C
      IF (ISPSAVE.NE.0) THEN
         write(ispsave,*)' 0 ',XA,YA
      END IF
C
      IF(LABON.EQ.0)THEN
      CALL XLPNUP(XA,YA)
      ELSE
      IF(IJOIN.GT.1)THEN
        CALL ZDRAWC(XJ,YJ,IJOIN)
      ENDIF
      IJOIN=1
      XJ(IJOIN)=XA
      YJ(IJOIN)=YA
      ENDIF
C
      RETURN
      END
