      SUBROUTINE ZPLTCH(X,Y,TEXT)
C
      REAL RAD
      REAL PIH
      REAL XOFF
      INTEGER IHTLAB
      REAL DX
      REAL ANGLE
      REAL DY
      REAL X
      REAL Y
      REAL ZANG
      REAL ZSTEP
      REAL ZLEN
      REAL ZCHAR
      INTEGER NLABEL
      INTEGER LABON
C
      CHARACTER TEXT*(*)
C
      COMMON/ZLABL/PIH,ZSTEP,ZLEN,ZCHAR,NLABEL,LABON,IHTLAB
C
C
      SAVE ANGLE
C   CENTRE TEXT
      RAD=PIH/90.
      XOFF=IHTLAB*6.00E-4
      DX=XOFF*SIN(ANGLE*RAD)
      DY=-XOFF*COS(ANGLE*RAD)
      CALL XCHARC(X+DX,Y+DY,TEXT)
      RETURN
      ENTRY ZANGLE(ZANG)
      ANGLE=ZANG
      CALL XCHORI(ANGLE)
      END
