C
      SUBROUTINE ZPROJC(X,Y,IB,IA)
C
      INTEGER IDUB,IA,IPLOT,IB,IFIN
      REAL    D,E,X1,Y1,DELT2,X1L,Y1L,XX1,YY1,XX2,YY2
      REAL    Y,DELT1,DELT4X,DELT4Y,XX3,YY3,XX2T,YY2T
      REAL    XDUM,YDUM,DELT3Y,DELT3X,X3,Y3,X2,Y2,Y11
      REAL    RCS,R1,QSTEP,RXY,CS1,RCS1,SALON1,SALAT1
      REAL    CALAT1,YT,XA,XLL,X2L,Y2L,X,CALON1
C
      include 'zpltpm.cmn'
c      COMMON/ZPLTPM/CX,CY,ALONS,ALATS,SALATS,CALATS,RC,AMP,SNWD,CSWD
c     :,CENT,ISTL,SWITCH,XH,YH,RAD,YEND,DX,DY,YTOP,RDX,RDY,RTOP,NM,NJ
c     :,MG,JG,JG2,JG2P,MGP,MGHP,DLONG,DLAT,PI,SVAGL,CVAGL,SROT,CROT,Q
c     :,ROUSN,ROUCS,PI2,ALFA,BETA,FANST,FANED,ITRUNC,AMQ,AMR,AK,YB,AB
c     :,ICOASRD,INCCST,ICOORD,CENTY,X1LIM,X2LIM,Y1LIM,Y2LIM
c     :,Z1STEP,Z1CHAR,IZTYPE,IVECTC,ARM
C
C
C1.2
C1.5  SAVE DELT2,XX2,YY2,IPLOT,X2,Y2,DELT3X,DELT3Y
      SAVE DELT2,XX2,YY2,IPLOT,X2,Y2,DELT3X,DELT3Y,X2L,Y2L,X1L,Y1L
      DATA X1,Y1/2*0./,DELT2/0.0/,X1L,Y1L,XX2,YY2/0.0,0.0,0.0,0.0/
      D(P1,P2,B1,B2)=B1-P1*(B2-B1)/(P2-P1)
      E(P1,P2,B1,B2,BB)=(BB-P1)*(B2-B1)/(P2-P1) + B1
c
      IDUB=0
      IF(ISTL.NE.0) GOTO 900
       XX1=X
       YY1=Y
       IA=1
       GOTO 980
  900 GOTO (901,902,934,934,956,956,978,978,990) ISTL
  901 CONTINUE
       X1=RAD*X-CENT
C1.2
       YY1=2.*Y*YH/PI-CENTY
       IPLOT=1
       DELT1=0.
       IF(X1.GT. XH ) DELT1=-1.
       IF(X1.LT.-XH ) DELT1= 1.
       DELT4X=0.0
       DELT4Y=0.0
       XX1=X1+DELT1*2.*XH
       IF(DELT2.NE.DELT1.AND.IB.EQ.1)  THEN
         XX3= XH*(DELT2-DELT1)
         XX2=XX2-2.*XX3
         YY3=D(XX1+XX3,XX2+XX3,YY1,YY2)
C1.2
         XX2T=XX2
         YY2T=YY2
         XDUM=XX1
         YDUM=YY1
         XX1=XX3
         YY1=YY3
COPY  OF CODE LATER ON
      IF(XX1.GT.X2LIM)DELT4X=1.0
      IF(XX1.LT.X1LIM)DELT4X=-1.0
      IF(YY1.GT.Y2LIM)DELT4Y=1.0
      IF(YY1.LT.Y1LIM)DELT4Y=-1.0
      IF(IB.NE.1)THEN
      CALL ZPENUP(XX1,YY1)
      ELSE
      IF(DELT3Y.EQ.DELT4Y.AND.DELT3Y.NE.0.0)THEN
        CALL ZPENUP(XX1,YY1)
      ELSEIF(DELT3X.EQ.DELT4X.AND.DELT3X.NE.0.0)THEN
        CALL ZPENUP(XX1,YY1)
      ELSEIF(DELT3X.EQ.DELT4X)THEN
        IF(DELT3Y.EQ.DELT4Y)THEN
          CALL ZPENDN(XX1,YY1)
        ELSEIF(DELT3Y.LT.0.0)THEN
          XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
          CALL ZPENUP(XX3,Y1LIM)
          IF(DELT4Y.EQ.0.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       CALL ZPENDN(XX3,Y2LIM)
       CALL ZPENUP(XX1,YY1)
          ENDIF
        ELSEIF(DELT3Y.EQ.0.0)THEN
          IF(DELT4Y.GT.0.0)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       CALL ZPENDN(XX3,Y2LIM)
       CALL ZPENUP(XX1,YY1)
          ELSE
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       CALL ZPENDN(XX3,Y1LIM)
       CALL ZPENUP(XX1,YY1)
          ENDIF
        ELSEIF(DELT3Y.GT.0.0)THEN
          XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
          CALL ZPENUP(XX3,Y2LIM)
          IF(DELT4Y.EQ.0.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       CALL ZPENDN(XX3,Y1LIM)
       CALL ZPENUP(XX1,YY1)
          ENDIF
        ELSE
          PRINT*,' SHOULD NOT BE HERE '
        ENDIF
      ELSEIF(DELT3X.LT.DELT4X)THEN
        IFIN=0
        IF(DELT3X.LT.0.)THEN
          YY3=E(XX2T,XX1,YY2T,YY1,X1LIM)
          IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y2LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y1LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSE
       CALL ZPENUP(X1LIM,YY3)
          ENDIF
        ENDIF
        IF(IFIN.EQ.0)THEN
          IF(DELT4X.EQ.0.AND.DELT4Y.EQ.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       YY3=E(XX2T,XX1,YY2T,YY1,X2LIM)
       IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y2LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y1LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSE
       CALL ZPENDN(X2LIM,YY3)
       CALL ZPENUP(XX1,YY1)
       ENDIF
          ENDIF
        ENDIF
      ELSEIF(DELT3X.GT.DELT4X)THEN
        IFIN=0
        IF(DELT3X.GT.0.0)THEN
          YY3=E(XX2T,XX1,YY2T,YY1,X2LIM)
          IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y2LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y1LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSE
       CALL ZPENUP(X2LIM,YY3)
          ENDIF
        ENDIF
        IF(IFIN.EQ.0)THEN
          IF(DELT4X.EQ.0.AND.DELT4Y.EQ.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       YY3=E(XX2T,XX1,YY2T,YY1,X1LIM)
       IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y2LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y1LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSE
       CALL ZPENDN(X1LIM,YY3)
       CALL ZPENUP(XX1,YY1)
       ENDIF
          ENDIF
        ENDIF
      ELSE
        PRINT*,' HOW THE HELL DID IT GET TO HERE '
        PRINT*,' X1LIM, ETC',X1LIM,X2LIM,Y1LIM,Y2LIM
        PRINT*,XX2T,XX1,YY2T,YY1
      ENDIF
      ENDIF
COPY  ENDS HERE
         CALL ZPENUP(-XX3,YY3)
         XX1=XDUM
         YY1=YDUM
         XX2=-XX3
         YY2=YY3
         DELT3X=0.0
         IF(XX2.GT.X2LIM)DELT3X=1.0
         IF(XX2.LT.X1LIM)DELT3X=-1.0
         DELT4X=0.0
         DELT4Y=0.0
       ENDIF
       GOTO 979
  902 CONTINUE
       IF(AB.NE.0.) THEN
         X1=X-ALONS
         DELT1=0.
         IF(X1.GT. PI ) DELT1=-1.
         IF(X1.LT.-PI ) DELT1= 1.
         X1=X1+DELT1*PI2
         Y1=Y
         IF(DELT2.NE.DELT1.AND.IB.EQ.1.AND.AK.NE.1.)  THEN
      X3= PI*(DELT2-DELT1)
      Y3=D(X1+X3,X2-X3,Y1,Y2)
      IDUB=1
      X2=X1
      Y2=Y1
      X1=X3
      Y1=Y3
      X3=X2
      Y3=Y2
         ENDIF
       ENDIF
  903    CONTINUE
       IF(AB.NE.0.) THEN
         IF(Q.EQ.0.) THEN
      Y11=.25*PI+0.5*Y1
      IF(ABS(Y11).LT.1.E-5) Y11=1.E-5
         ELSE
      Y11=.25*PI-0.5*Q*Y1
      ENDIF
         IF(ABS(Y11-.5*PI).LT.1.E-5) Y11=Y11-1.E-5
         IF(Q.EQ.0.) THEN
      XX1=AB*YH*X1
      YY1=(YB+AB*LOG(TAN(Y11)))*YH
         ELSEIF(AK.EQ.1.) THEN
      RCS=AB*YH*TAN(Y11)
      XX1=RCS*SIN(X1)
      YY1=YH*YB-Q*RCS*COS(X1)
         ELSE
      RCS=AB*YH*(TAN(Y11))**AK
      XX1=RCS*SIN(AK*X1)
      YY1=YH*YB-Q*RCS*COS(AK*X1)
         ENDIF
         IF(ABS(XX1).LE.XH.AND.ABS(YY1).LE.YH) THEN
      IF(IB.EQ.1.AND.IPLOT.EQ.1) GOTO 979
      IPLOT=1
      IF(IB.NE.1) GOTO 979
      IF(XX2.LT.-XH) THEN
          YY2=D(XX1+XH,XX2+XH,YY1,YY2)
          XX2=-XH
      ELSEIF(XX2.GT. XH) THEN
          YY2=D(XX1-XH,XX2-XH,YY1,YY2)
          XX2= XH
      ENDIF
      IF(YY2.LT.-YH) THEN
          XX2=D(YY1+YH,YY2+YH,XX1,XX2)
          YY2=-YH
      ELSEIF(YY2.GT. YH) THEN
          XX2=D(YY1-YH,YY2-YH,XX1,XX2)
          YY2= YH
      ENDIF
      CALL ZPENUP(XX2,YY2)
      GOTO 979
         ELSEIF(IPLOT.NE.1.OR.IB.NE.1) THEN
      IPLOT=0
      GOTO 979
         ELSE
      IF(XX1.LE.-XH.AND.XX2.GT.-XH) THEN
          YY1=D(XX1+XH,XX2+XH,YY1,YY2)
          XX1=-XH
      ELSEIF(XX1.GE. XH.AND.XX2.LT. XH) THEN
          YY1=D(XX1-XH,XX2-XH,YY1,YY2)
          XX1= XH
      ENDIF
      IF(YY1.LE.-YH.AND.YY2.GT.-YH) THEN
          XX1=D(YY1+YH,YY2+YH,XX1,XX2)
          YY1=-YH
      ELSEIF(YY1.GE. YH.AND.YY2.LT. YH) THEN
          XX1=D(YY1-YH,YY2-YH,XX1,XX2)
          YY1= YH
      ENDIF
         ENDIF
         IPLOT=0
         IF(ABS(XX2).EQ.XH.OR.ABS(YY2).EQ.YH) GOTO 979
         CALL ZPENDN(XX1,YY1)
         GOTO 979
       ENDIF
       X1=RAD*X-CENT
       Y1=    Y
       DELT1=0.
       IF(X1.GT. XH ) DELT1=-1.
       IF(X1.LT.-XH ) DELT1= 1.
       XX1=X1+DELT1*2.*XH
       IF(ABS(Y1).GT.YEND) THEN
         IPLOT=0
         YY1=YH*Y1/ABS(Y1)
         GOTO 979
       ENDIF
       YY1=XH *LOG((1.+SIN(Y1))/COS(Y1))/PI
       IF(DELT2.NE.DELT1.AND.IB.EQ.1)  THEN
         XX3= XH*(DELT2-DELT1)
         XX2=XX2-2.*XX3
         YY3=D(XX1+XX3,XX2+XX3,YY1,YY2)
         CALL ZPENDN( XX3,YY3)
         CALL ZPENUP(-XX3,YY3)
       ENDIF
       IF(IPLOT.NE.1) THEN
         CALL ZPENUP(XX1,YY1)
         IPLOT=1
       ENDIF
       GOTO 979
  934 CONTINUE
       X1=X-ALONS
       Y1=Y
       DELT1=SIN(Y1*RC)-CSWD
       IF(DELT1.LT.-0.5) THEN
         IPLOT=0
           XX1=0.0
           YY1=0.0 
         GOTO 979
       ENDIF
       R1=COS(Y1)*AMP*AMQ/(1+(SWITCH-SVAGL*(1-SWITCH))*(DELT1+CSWD))
       XX1= SIN(X1)*R1
       YY1=-COS(X1)*R1*RC
       IF(BETA.NE.PI2.AND.ITRUNC.EQ.1) THEN
         QSTEP=X1   -ALFA
         IF (QSTEP.GT. PI) QSTEP=MOD(QSTEP+PI,PI2)-PI
         IF (QSTEP.LE.-PI) QSTEP=MOD(QSTEP-PI,PI2)+PI
         IF (ABS(QSTEP).GT.0.5*BETA) THEN
            IPLOT=0
            GOTO 979
         ELSEIF(IPLOT.EQ.0..AND.DELT1.GE.0.) THEN
            CALL ZPENUP(XX1,YY1)
           IPLOT=1
        ENDIF
       ENDIF
       IF(IB.NE.1) THEN
         IF(DELT1.GE.0.) THEN
      IPLOT=1
         ELSE
      IPLOT=0
         ENDIF
         GOTO 979
       ENDIF
       IF(DELT1.LT.0.0.AND.DELT2.GE.0.0) THEN
         XX3=D(DELT1,DELT2,XX1,XX2)
         YY3=D(DELT1,DELT2,YY1,YY2)
         RXY=AMP*AMR/SQRT(XX3*XX3+YY3*YY3)
         XX3=XX3*RXY
         YY3=YY3*RXY
         CALL ZPENDN(XX3,YY3)
         IPLOT=0
       ELSEIF(DELT1.GE.0.0.AND.DELT2.LT.0.0) THEN
         XX3=D(DELT1,DELT2,XX1,XX2)
         YY3=D(DELT1,DELT2,YY1,YY2)
         RXY=AMP*AMR/SQRT(XX3*XX3+YY3*YY3)
         XX3=XX3*RXY
         YY3=YY3*RXY
         CALL ZPENUP(XX3,YY3)
         IPLOT=1
       ENDIF
       GOTO 979
  956 CONTINUE
       X1=X-ALONS
       Y1=Y
       DELT1=COS(X1)
       IF(DELT1.LT.-0.5) THEN
         IPLOT=0
         GOTO 979
       ENDIF
       CS1=COS(Y1)
       RCS1=AMP/(1.+CS1*DELT1*SWITCH)
       XX1=CS1*SIN(X1)*RCS1
       YY1=SIN(Y1)*RCS1
       IF(IB.NE.1) THEN
         IF(DELT1.GE.0.) THEN
      IPLOT=1
         ELSE
      IPLOT=0
         ENDIF
         GOTO 979
       ENDIF
       IF(DELT1.LT.0.0.AND.DELT2.GE.0.0) THEN
         XX3=D(DELT1,DELT2,XX1,XX2)
         YY3=D(DELT1,DELT2,YY1,YY2)
         RXY=AMP/SQRT(XX3*XX3+YY3*YY3)
         XX3=XX3*RXY
         YY3=YY3*RXY
         CALL ZPENDN(XX3,YY3)
         IPLOT=0
       ELSEIF(DELT1.GE.0.0.AND.DELT2.LT.0.0) THEN
         XX3=D(DELT1,DELT2,XX1,XX2)
         YY3=D(DELT1,DELT2,YY1,YY2)
         RXY=AMP/SQRT(XX3*XX3+YY3*YY3)
         XX3=XX3*RXY
         YY3=YY3*RXY
         CALL ZPENUP(XX3,YY3)
         IPLOT=1
       ENDIF
       GOTO 979
  978 CONTINUE
       SALON1=SIN(X-ALONS)
       CALON1=COS(X-ALONS)
       SALAT1=SIN(Y)
       CALAT1=COS(Y)
       DELT1=SALATS*SALAT1+CALATS*CALAT1*CALON1-CSWD
       IF(DELT1.LT.-0.5) THEN
         IPLOT=0
         GOTO 979
       ENDIF
       XX1=CALAT1*SALON1
       YY1=(CALATS*SALAT1-CALAT1*SALATS*CALON1)
       XX3=XX1*AMP*AMQ/(1.+(SWITCH-SVAGL*(1.-SWITCH))*(DELT1+CSWD))
       YY3=YY1*AMP*AMQ/(1.+(SWITCH-SVAGL*(1.-SWITCH))*(DELT1+CSWD))
       XX1= CROT*XX3-SROT*YY3
       YY1= SROT*XX3+CROT*YY3
       IF(IB.NE.1) THEN
         IF(DELT1.GE.0.) THEN
      IPLOT=1
         ELSE
      IPLOT=0
         ENDIF
         GOTO 979
       ENDIF
       IF(DELT1.LT.0.0.AND.DELT2.GE.0.0) THEN
         XX3=D(DELT1,DELT2,XX1,XX2)
         YY3=D(DELT1,DELT2,YY1,YY2)
         RXY=AMP*AMR/SQRT(XX3*XX3+YY3*YY3)
         XX3=XX3*RXY
         YY3=YY3*RXY
         CALL ZPENDN(XX3,YY3)
         IPLOT=0
       ELSEIF(DELT1.GE.0.0.AND.DELT2.LT.0.0) THEN
         XX3=D(DELT1,DELT2,XX1,XX2)
         YY3=D(DELT1,DELT2,YY1,YY2)
         RXY=AMP*AMR/SQRT(XX3*XX3+YY3*YY3)
         XX3=XX3*RXY
         YY3=YY3*RXY
         CALL ZPENUP(XX3,YY3)
         IPLOT=1
       ENDIF
       GO TO 979
 990   CONTINUE
       X1=X-CENT*PI/XH
       YT=Y
C1.5
       X1L=X1
       Y1L=Y
C1.5
       CALL XSINX(YT,XA,PI)
       XLL=2.*ARM*COS(XA)
       X1=X1/PI*XLL
       YY1=ARM*SIN(XA)
       DELT1=0.
       IPLOT=1
C1.5   IF(X1.GT.XLL)DELT1=-1.
C1.5   IF(X1.LT.-XLL)DELT1= 1.
C1.5   XX1=X1+DELT1*2.*XLL
C1.5   IF(DELT1.NE.DELT2.AND.IB.EQ.1)THEN
C1.5     XX3=XLL*(DELT2-DELT1)
C1.5       XX2=XX2-2.*XX3
C1.5       YY3=D(XX1+XX3,XX2+XX3,YY1,YY2)
       IF(X1L.GT.PI)DELT1=-1.
       IF(X1L.LT.-PI)DELT1= 1.
       XX1=X1+DELT1*2.*XLL
       IF(DELT1.NE.DELT2.AND.IB.EQ.1)THEN
         XX3=PI*(DELT2-DELT1)
         X1L=X1L+DELT1*2.*PI
         X2L=X2L-2.*XX3
         YY3=D(X1L+XX3,X2L+XX3,Y1L,Y2L)
         CALL XSINX(YY3,XA,PI)
         XLL=2.*ARM*COS(XA)
         XX3=XX3/PI*XLL
         YY3=ARM*SIN(XA)
C1.5
       CALL ZPENDN(XX3,YY3)
       CALL ZPENUP(-XX3,YY3)
       ENDIF
       GO TO 979
  979 CONTINUE
      X2=X1
      Y2=Y1
      DELT2=DELT1
      XX2T=XX2
      YY2T=YY2
      XX2=XX1
      YY2=YY1
C1.5
      X2L=X1L
      Y2L=Y1L
C1.5
      IA=IPLOT
      IF(IDUB.EQ.1) THEN
       IF(IPLOT.EQ.1) THEN
         CALL ZPENDN( XX1,YY1)
         CALL ZPENUP(-XX1,YY1)
       ENDIF
       XX2=-XX1
       X1=X3
       Y1=Y3
       IDUB=0
       GOTO 903
      ENDIF
      IF(IPLOT.NE.1) RETURN
  980 CONTINUE
C1.2
      IF(ISTL.EQ.1)THEN
      IF(XX1.GT.X2LIM)DELT4X=1.0
      IF(XX1.LT.X1LIM)DELT4X=-1.0
      IF(YY1.GT.Y2LIM)DELT4Y=1.0
      IF(YY1.LT.Y1LIM)DELT4Y=-1.0
      IF(IB.NE.1)THEN
      IF(ICOORD.EQ.0)THEN
        CALL ZPENUP(XX1,YY1)
      ELSE
        X=XX1
        Y=YY1
      ENDIF
      ELSE
      IF(DELT3Y.EQ.DELT4Y.AND.DELT3Y.NE.0.0)THEN
        CALL ZPENUP(XX1,YY1)
      ELSEIF(DELT3X.EQ.DELT4X.AND.DELT3X.NE.0.0)THEN
        CALL ZPENUP(XX1,YY1)
      ELSEIF(DELT3X.EQ.DELT4X)THEN
        IF(DELT3Y.EQ.DELT4Y)THEN
          CALL ZPENDN(XX1,YY1)
        ELSEIF(DELT3Y.LT.0.0)THEN
          XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
          CALL ZPENUP(XX3,Y1LIM)
          IF(DELT4Y.EQ.0.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       CALL ZPENDN(XX3,Y2LIM)
       CALL ZPENUP(XX1,YY1)
          ENDIF
        ELSEIF(DELT3Y.EQ.0.0)THEN
          IF(DELT4Y.GT.0.0)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       CALL ZPENDN(XX3,Y2LIM)
       CALL ZPENUP(XX1,YY1)
          ELSE
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       CALL ZPENDN(XX3,Y1LIM)
       CALL ZPENUP(XX1,YY1)
          ENDIF
        ELSEIF(DELT3Y.GT.0.0)THEN
          XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
          CALL ZPENUP(XX3,Y2LIM)
          IF(DELT4Y.EQ.0.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       CALL ZPENDN(XX3,Y1LIM)
       CALL ZPENUP(XX1,YY1)
          ENDIF
        ELSE
          PRINT*,' SHOULD NOT BE HERE '
        ENDIF
      ELSEIF(DELT3X.LT.DELT4X)THEN
        IFIN=0
        IF(DELT3X.LT.0.)THEN
          YY3=E(XX2T,XX1,YY2T,YY1,X1LIM)
          IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y2LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y1LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSE
       CALL ZPENUP(X1LIM,YY3)
          ENDIF
        ENDIF
        IF(IFIN.EQ.0)THEN
          IF(DELT4X.EQ.0.AND.DELT4Y.EQ.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       YY3=E(XX2T,XX1,YY2T,YY1,X2LIM)
       IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y2LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y1LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSE
       CALL ZPENDN(X2LIM,YY3)
       CALL ZPENUP(XX1,YY1)
       ENDIF
          ENDIF
        ENDIF
      ELSEIF(DELT3X.GT.DELT4X)THEN
        IFIN=0
        IF(DELT3X.GT.0.0)THEN
          YY3=E(XX2T,XX1,YY2T,YY1,X2LIM)
          IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y2LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
       CALL ZPENUP(XX3,Y1LIM)
       ELSE
       CALL ZPENUP(XX1,YY1)
       IFIN=1
       ENDIF
          ELSE
       CALL ZPENUP(X2LIM,YY3)
          ENDIF
        ENDIF
        IF(IFIN.EQ.0)THEN
          IF(DELT4X.EQ.0.AND.DELT4Y.EQ.0)THEN
       CALL ZPENDN(XX1,YY1)
          ELSE
       YY3=E(XX2T,XX1,YY2T,YY1,X1LIM)
       IF(YY3.GT.Y2LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y2LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y2LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSEIF(YY3.LT.Y1LIM)THEN
       XX3=E(YY2T,YY1,XX2T,XX1,Y1LIM)
       IF(XX3.LT.X2LIM.AND.XX3.GT.X1LIM)THEN
         CALL ZPENDN(XX3,Y1LIM)
         CALL ZPENUP(XX1,YY1)
       ELSE
         CALL ZPENUP(XX1,YY1)
       ENDIF
       ELSE
       CALL ZPENDN(X1LIM,YY3)
       CALL ZPENUP(XX1,YY1)
       ENDIF
          ENDIF
        ENDIF
      ELSE
        PRINT*,' HOW THE HELL DID IT GET TO HERE '
        PRINT*,' X1LIM, ETC',X1LIM,X2LIM,Y1LIM,Y2LIM
        PRINT*,XX2T,XX1,YY2T,YY1
      ENDIF
      ENDIF
      DELT3X=DELT4X
      DELT3Y=DELT4Y
      ELSE
      IF(IB.NE.1) THEN
      IF(ICOORD.EQ.0)THEN
        CALL ZPENUP(XX1,YY1)
      ELSE
        X=XX1
        Y=YY1
      ENDIF
      IPLOT=1
      ELSE
      CALL ZPENDN(XX1,YY1)
      ENDIF
      ENDIF
      RETURN
      END
