      SUBROUTINE ZVECTC(U,V,ALO,ALA,MD,NMG,NJG,NUV,UM)
c
      INTEGER MD,NMG,NJG,NUV
      REAL    UM
      REAL    U(MD,*),V(MD,*),ALO(*),ALA(*)
C
      include 'zpltpm.cmn'

c      COMMON/ZPLTPM/CX,CY,ALONS,ALATS,SALATS,CALATS,RC,AMP,SNWD,CSWD
c     :,CENT,ISTL,SWITCH,XH,YH,RAD,YEND,DX,DY,YTOP,RDX,RDY,RTOP,NM,NJ
c     :,MG,JG,JG2,JG2P,MGP,MGHP,DLONG,DLAT,PI,SVAGL,CVAGL,SROT,CROT,Q
c     :,ROUSN,ROUCS,PI2,ALFA,BETA,FANST,FANED,ITRUNC,AMQ,AMR,AK,YB,AB
c     :,ICOASRD,INCCST,ICOORD,CENTY,X1LIM,X2LIM,Y1LIM,Y2LIM
c     :,Z1STEP,Z1CHAR,IZTYPE,IVECTC,ARM
C
C
      IVECTC=1
      CALL ZVECTA(U,V,ALO,ALA,MD,NMG,NJG,NUV,UM)
      IVECTC=0
      RETURN
      END
