      SUBROUTINE ZVECTA(U,V,ALO,ALA,MD,NMG,NJG,NUV,UM)
C
      INTEGER MD,NUV,NUVY,NMG,I,J,K,ILAM,NJG,JTHE
      REAL    DMASK,FINT,RS,DX2,DX1,DY1,DY2,DE,RSCALE
      REAL    UM,SCALE,SROTAT,CROTAT,ALOMIN,XO,YO,X,Y
      REAL    ROUSQ,ALAM,X1,YSN,Y1,ALAM1,THETA,RDMG
      REAL    U1,V1,U2,V2,U3,V3,U4,V4,U5,V5
      REAL    COSL,SINL,SALAT1,CALAT1,SALON1,CALON1
      REAL    CSL,SNL,UP,VP,XE,YE,XC,YC,XD,YD,XA,YA
      REAL    SLOPE,SLOPE2,ALEN2,DDX,DDY,AFACA,ALEN1
C
      REAL U(MD,*),V(MD,*),ALO(*),ALA(*)
C
      include 'zpltpm.cmn'
c      COMMON/ZPLTPM/CX,CY,ALONS,ALATS,SALATS,CALATS,RC,AMP,SNWD,CSWD
c     :,CENT,ISTL,SWITCH,XH,YH,RAD,YEND,DX,DY,YTOP,RDX,RDY,RTOP,NM,NJ
c     :,MG,JG,JG2,JG2P,MGP,MGHP,DLONG,DLAT,PI,SVAGL,CVAGL,SROT,CROT,Q
c     :,ROUSN,ROUCS,PI2,ALFA,BETA,FANST,FANED,ITRUNC,AMQ,AMR,AK,YB,AB
c     :,ICOASRD,INCCST,ICOORD,CENTY,X1LIM,X2LIM,Y1LIM,Y2LIM
c     :,Z1STEP,Z1CHAR,IZTYPE,IVECTC,ARM
C
      PARAMETER(DMASK= -2.54E+34)
C
      FINT(H1,H2,H3,H4)=RS*((DX2*H1+DX1*H4)*DY2+(DX2*H2+DX1*H3)*DY1)
      IF(ISTL.EQ.0) GOTO 202
      IF(ISTL.EQ.3.OR.ISTL.EQ.5.OR.ISTL.EQ.7) RETURN
      IF(ISTL.LE.2) THEN
      DE=2.*XH/NUV
      NUVY=NUV*(YH/XH)
      RSCALE=DE/UM
      SCALE=1.
      SROTAT=0.
      CROTAT=1.
      ELSE
      DE=2./NUV
      NUVY=NUV
      RSCALE=AMP*DE/UM
      SCALE=AMP
      SROTAT=SQRT(0.5)
      CROTAT=SROTAT
      ENDIF
      ALOMIN=MIN(ALO(1),ALO(NMG))
      DO 201 J=1,NUVY+1
      DO 201 I=1,NUV +1
      XO=DE*(I-1-.5*NUV)
      YO=DE*(J-1-.5*NUVY)
      X= CROTAT*XO+SROTAT*YO
      Y=-SROTAT*XO+CROTAT*YO
      ROUSQ=X*X+Y*Y
      IF(ISTL.GT.2.AND.ROUSQ.GT.0.96) GOTO 201
      IF(ISTL.EQ.1.OR.ISTL.EQ.2.AND.AB.EQ.0.0) THEN
      ALAM=X/RAD+ALONS
      ELSEIF(Q.EQ.0.) THEN
      IF(ABS(X).GT.AB*YH*PI) GOTO 201
      ALAM=X/(AB*YH)+ALONS
      ELSE
      IF(ISTL.EQ.2) THEN
          X1=X
          YSN=(Y-YB*YH)*Q
      ELSEIF(ISTL.EQ.4) THEN
          X1=X
          YSN=RC*Y
      ELSEIF(ISTL.EQ.6) THEN
          X1=X
          YSN=-0.5*(1.-ROUSQ)
      ELSEIF(ISTL.EQ.8) THEN
          X1=( CROT*X+SROT*Y)/AMQ
          Y1=(-SROT*X+CROT*Y)/AMQ
          ROUSQ=ROUSQ/(AMQ*AMQ)
          YSN=Y1*SALATS-0.5*CALATS*(1.-ROUSQ)
      ENDIF
      IF(ABS(X1)+ABS(YSN).EQ.0.0) GOTO 201
      ALAM1=ATAN2(X1,-YSN)
      IF(ISTL.EQ.2) THEN
          IF(ABS(ALAM1).GT.AK*PI) GOTO 201
          ALAM1=ALAM1/AK
      ENDIF
      ALAM=ALAM1+ALONS
      IF(ISTL.EQ.4.AND.BETA.NE.PI2) THEN
          ALAM1=ALAM-ALONS-ALFA
          IF(ALAM1.GT. PI) ALAM1=MOD(ALAM1+PI,PI2)-PI
          IF(ALAM1.LE.-PI) ALAM1=MOD(ALAM1-PI,PI2)+PI
          IF(ABS(ALAM1).GE.0.5*BETA) GOTO 201
      ENDIF
      ENDIF
      IF(ALAM.LT.ALOMIN) ALAM=ALAM+PI2
      IF(ALAM.GE.ALOMIN+PI2) ALAM=ALAM-PI2
      IF(ISTL.EQ.1) THEN
C1.2
      THETA=0.5*PI*Y/YH + ALATS
      ELSEIF(ISTL.EQ.2) THEN
      IF(AB.EQ.0.) THEN
          THETA=2.*ATAN(EXP(Y/RAD))-0.5*PI
      ELSEIF(Q.EQ.0) THEN
          THETA=2.*ATAN(EXP((Y-YH*YB)/(YH*AB)))-0.5*PI
      ELSE
          THETA=.5*PI-2.*ATAN((SQRT(X*X+YSN*YSN)/(YH*AB))**(1./AK))
          THETA=THETA*Q
      ENDIF
      ELSEIF(ISTL.EQ.4) THEN
      THETA=RC*(0.5*PI-2.*ATAN(SQRT(ROUSQ)/AMQ))
      ELSEIF(ISTL.EQ.6) THEN
      THETA=ASIN(2.*Y/(1.+ROUSQ))
      ELSEIF(ISTL.EQ.8) THEN
      THETA=ASIN((Y1*CALATS+.5*(1.-ROUSQ)*SALATS)*2./(1.+ROUSQ))
      ENDIF
      DO  9 K=1,NMG-1
      DX1=ALAM-ALO(K)
      DX2=ALO(K+1)-ALAM
      IF(DX1.GE.0.0.AND.DX2.GT.0.0.OR.DX1.LT.0.0.AND.DX2.LE.0.0) THEN
      RDMG=1./(DX1+DX2)
      ILAM=K
      GOTO 10
      ENDIF
    9 CONTINUE
      GOTO 201
   10 CONTINUE
      DO 11 K=1,NJG-1
      DY1=THETA-ALA(K)
      DY2=ALA(K+1)-THETA
      IF(DY1.GE.0.0.AND.DY2.GT.0.0.OR.DY1.LT.0.0.AND.DY2.LE.0.0) THEN
      RS=RDMG/(DY1+DY2)
      JTHE=K
      GOTO 12
      ENDIF
   11 CONTINUE
      GOTO 201
   12 CONTINUE
      IF (U(ILAM,JTHE).EQ.DMASK) GO TO 201
      IF (U(ILAM+1,JTHE).EQ.DMASK) GO TO 201
      IF (U(ILAM,JTHE+1).EQ.DMASK) GO TO 201
      IF (V(ILAM,JTHE).EQ.DMASK) GO TO 201
      IF (V(ILAM+1,JTHE).EQ.DMASK) GO TO 201
      IF (V(ILAM,JTHE+1).EQ.DMASK) GO TO 201
      U1=U(ILAM  ,JTHE  )*RSCALE
      V1=V(ILAM  ,JTHE  )*RSCALE
      U2=U(ILAM  ,JTHE+1)*RSCALE
      V2=V(ILAM  ,JTHE+1)*RSCALE
      U3=U(ILAM+1,JTHE+1)*RSCALE
      V3=V(ILAM+1,JTHE+1)*RSCALE
      U4=U(ILAM+1,JTHE  )*RSCALE
      V4=V(ILAM+1,JTHE  )*RSCALE
      U5=FINT(U1,U2,U3,U4)
      V5=FINT(V1,V2,V3,V4)
      IF(ISTL.EQ.1.OR.ISTL.EQ.2.AND.(AB.EQ.0..OR.Q.EQ.0.)) THEN
      COSL=1.
      SINL=0.
      ELSEIF(ISTL.EQ.2) THEN
      COSL=COS(AK*ALAM1)
      SINL=SIN(AK*ALAM1)*Q
      ELSEIF(ISTL.EQ.4) THEN
      COSL=COS(ALAM-ALONS)
      SINL=SIN(ALAM-ALONS)*RC
      ELSEIF(ISTL.EQ.6) THEN
      SALAT1=SIN(THETA)
      CALAT1=COS(THETA)
      SALON1=SIN(ALAM-ALONS)
      CALON1=COS(ALAM-ALONS)
      COSL=0.5*(CALAT1+CALON1)*(1.+ROUSQ)
      SINL=0.5*SALAT1*SALON1*(1.+ROUSQ)
      ELSEIF(ISTL.EQ.8) THEN
      SALAT1=SIN(THETA)
      CALAT1=COS(THETA)
      SALON1=SIN(ALAM-ALONS)
      CALON1=COS(ALAM-ALONS)
      CSL=0.5*(CALAT1*CALATS+CALON1*(1.+SALAT1*SALATS))*(1.+ROUSQ)
      SNL=0.5*(SALAT1+SALATS)*SALON1*(1.+ROUSQ)
      COSL=CROT*CSL-SROT*SNL
      SINL=SROT*CSL+CROT*SNL
      ENDIF
      UP=U5*COSL-V5*SINL
      VP=U5*SINL+V5*COSL
      XO=X*SCALE
      YO=Y*SCALE
      XE=XO+UP
      YE=YO+VP
      IF(ISTL.LE.2.AND.(ABS(XE).GT.XH.OR.ABS(YE).GT.YH)) GOTO 201
      XC=XE-ROUCS*UP-ROUSN*VP
      YC=YE+ROUSN*UP-ROUCS*VP
      XD=XE-ROUCS*UP+ROUSN*VP
      YD=YE-ROUSN*UP-ROUCS*VP
      XA=XE-ROUCS*UP
      YA=YE-ROUCS*VP
C
C     Centre arrows
C
      IF(IVECTC.EQ.1)THEN
      IF(XO.NE.XE)THEN
        SLOPE=(YE-YO)/(XE-XO)
        SLOPE2=SLOPE*SLOPE
        ALEN2=(XE-XO)*(XE-XO)+(YE-YO)*(YE-YO)
        DDX=0.5*SQRT(ALEN2/(1.+SLOPE2))
        DDY=SLOPE*DDX
        IF(XE.GT.XO)THEN
          AFACA=1.
        ELSE
          AFACA=-1.
        ENDIF
        XA=XA-DDX*AFACA
        XO=XO-DDX*AFACA
        XE=XE-DDX*AFACA
        XC=XC-DDX*AFACA
        XD=XD-DDX*AFACA
        YA=YA-DDY*AFACA
        YO=YO-DDY*AFACA
        YE=YE-DDY*AFACA
        YC=YC-DDY*AFACA
        YD=YD-DDY*AFACA
      ELSE
        ALEN1=0.5*(YE-YO)
        YO=YO-ALEN1
        YE=YE-ALEN1
        YC=YC-ALEN1
        YD=YD-ALEN1
        YA=YA-ALEN1
      ENDIF
      ENDIF
C1.2
      IF(ISTL.EQ.1)THEN
      IF(XO.LT.X1LIM.OR.XO.GT.X2LIM)GO TO 201
      IF(YO.LT.Y1LIM.OR.YO.GT.Y2LIM)GO TO 201
      ENDIF
      CALL ZPENUP(XO,YO)
      IF(ROUSN.GE.0.0) THEN
      CALL ZPENDN(XE,YE)
      CALL ZPENDN(XC,YC)
      CALL ZPENUP(XD,YD)
      ELSE
      CALL ZPENDN(XA,YA)
      CALL ZPENUP(XE,YE)
      CALL ZPENDN(XC,YC)
      CALL ZPENDN(XD,YD)
      ENDIF
      CALL ZPENDN(XE,YE)
  201 CONTINUE
      RETURN
  202 DO 203 J=1,NJG
      YO=ALA(J)
      DO 203 I=1,NMG
      XO=ALO(I)
      UP=U(I,J)*UM
      VP=V(I,J)*UM
      XE=XO+UP
      YE=YO+VP
      XC=XE-ROUCS*UP-ROUSN*VP
      YC=YE+ROUSN*UP-ROUCS*VP
      XD=XE-ROUCS*UP+ROUSN*VP
      YD=YE-ROUSN*UP-ROUCS*VP
C
C     Centre arrows
C
      IF(IVECTC.EQ.1)THEN
      IF(XO.NE.XE)THEN
        SLOPE=(YE-YO)/(XE-XO)
        SLOPE2=SLOPE*SLOPE
        ALEN2=(XE-XO)*(XE-XO)+(YE-YO)*(YE-YO)
        DDX=0.5*SQRT(ALEN2/(1.+SLOPE2))
        DDY=SLOPE*DDX
        IF(XE.GT.XO)THEN
          AFACA=1.
        ELSE
          AFACA=-1.
        ENDIF
        XO=XO-DDX*AFACA
        XE=XE-DDX*AFACA
        XC=XC-DDX*AFACA
        XD=XD-DDX*AFACA
        YO=YO-DDY*AFACA
        YE=YE-DDY*AFACA
        YC=YC-DDY*AFACA
        YD=YD-DDY*AFACA
      ELSE
        ALEN1=0.5*(YE-YO)
        YO=YO-ALEN1
        YE=YE-ALEN1
        YC=YC-ALEN1
        YD=YD-ALEN1
      ENDIF
      ENDIF
      CALL ZPENUP(XO,YO)
      CALL ZPENDN(XE,YE)
      CALL ZPENDN(XC,YC)
      CALL ZPENUP(XD,YD)
      CALL ZPENDN(XE,YE)
  203 CONTINUE
      RETURN
      END
