      SUBROUTINE ZXYREF
C
      INTEGER NJ1,I,J,IB,IA,MGR,IM
      REAL    XST,X,YLAT,FAI,ALONG,FLONG,ALST,RD,RST
      REAL    RT,CSRT,RSTEP,QSTEP,ASW,RCS,RSINM,ALATJ
      REAL    CSFAI,SIFAI,X1,X2,XAN
C
      include 'zpltpm.cmn'
c      COMMON/ZPLTPM/CX,CY,ALONS,ALATS,SALATS,CALATS,RC,AMP,SNWD,CSWD
c     :,CENT,ISTL,SWITCH,XH,YH,RAD,YEND,DX,DY,YTOP,RDX,RDY,RTOP,NM,NJ
c     :,MG,JG,JG2,JG2P,MGP,MGHP,DLONG,DLAT,PI,SVAGL,CVAGL,SROT,CROT,Q
c     :,ROUSN,ROUCS,PI2,ALFA,BETA,FANST,FANED,ITRUNC,AMQ,AMR,AK,YB,AB
c     :,ICOASRD,INCCST,ICOORD,CENTY,X1LIM,X2LIM,Y1LIM,Y2LIM
c     :,Z1STEP,Z1CHAR,IZTYPE,IVECTC,ARM
C
      IF(ISTL.EQ.0) RETURN
      NJ1=NJ
      IF(RTOP.EQ.0.5*PI) NJ1=NJ-1
      GOTO (12,15,34,34,56,56,78,78,80) ISTL
   12 CONTINUE
       CALL ZPENUP(X1LIM,Y1LIM)
       CALL ZPENDN(X2LIM,Y1LIM)
       CALL ZPENDN(X2LIM,Y2LIM)
       CALL ZPENDN(X1LIM,Y2LIM)
       CALL ZPENDN(X1LIM,Y1LIM)
       XST=MOD(CX+180.,DX)*XH/180.
       DO 111 I=-NM,NM
       X=I*DX*XH/180.-XST
       IF(X.GE.X2LIM.OR.X.LE.X1LIM) GOTO 111
       CALL ZPENUP(X,Y1LIM)
       CALL ZPENDN(X,Y2LIM)
  111    CONTINUE
       DO 122 I=-NJ1,NJ1
       YLAT=-(2.*I*RDY*YH/PI - CENTY)
       IF(YLAT.GE.Y2LIM.OR.YLAT.LE.Y1LIM) GO TO 122
       CALL ZPENUP(X1LIM,YLAT)
       CALL ZPENDN(X2LIM,YLAT)
  122    CONTINUE
       RETURN
   15 CONTINUE
       CALL ZPENUP(-XH,-YH)
       CALL ZPENDN( XH,-YH)
       CALL ZPENDN( XH, YH)
       CALL ZPENDN(-XH, YH)
       CALL ZPENDN(-XH,-YH)
       XST=MOD(CX+180.,DX)*XH/180.
       IF(ISTL.EQ.1.OR.AB.EQ.0..OR.AK.EQ.1.) GOTO 8
       DO 7 I=1,2
       X=(1.5-I)*PI2+ALONS
       DO 7 J=-NJ ,NJ
       IF(J.EQ.NJ.OR.J.EQ.-NJ) THEN
         FAI=RTOP*(-J)/ABS(J)
       ELSE
         FAI=( -J )*RDY
       ENDIF
       IF(J.EQ.-NJ ) THEN
         IB=0
       ELSE
         IB=1
       ENDIF
    7    CALL ZPROJC(X,FAI,IB,IA)
    8    DO 11 I=-NM,NM
       IF(ISTL.EQ.1.OR.AB.EQ.0) GOTO 10
       IF(I.LE.0) GOTO 11
       X=I*RDX
       IF(AK.NE.1..AND.ABS(X+ALONS).EQ.PI) GOTO 11
       DO 9 J=-NJ1,NJ1
       IF(J.EQ.NJ.OR.J.EQ.-NJ) THEN
         FAI=RTOP*(-J)/ABS(J)
       ELSE
         FAI=( -J )*RDY
       ENDIF
       IF(J.EQ.-NJ1) THEN
         IB=0
       ELSE
         IB=1
       ENDIF
    9    CALL ZPROJC(X,FAI,IB,IA)
       GOTO 11
   10    X=I*DX*XH/180.-XST
       IF(ABS(X).GE.XH) GOTO 11
       CALL ZPENUP(X,-YH)
       CALL ZPENDN(X, YH)
   11    CONTINUE
       DO 22 I=-NJ1,NJ1
       IF(ISTL.EQ.1.OR.AB.EQ.0.) GOTO 13
       IF(I.EQ.NJ.OR.I.EQ.-NJ) THEN
         FAI=RTOP*(-I)/ABS(I)
       ELSE
         FAI=( -I )*RDY
       ENDIF
       IF(ABS(FAI).EQ.0.5*PI) GOTO 22
       DO 14 J=1,MGP
       ALONG=(J-1.)*DLONG
       IF(J.EQ.1) THEN
         IB=0
       ELSE
         IB=1
       ENDIF
   14    CALL ZPROJC(ALONG,FAI,IB,IA)
       GOTO 22
   13    FAI=-I*RDY
       IF(ISTL.EQ.1) THEN
         YLAT=2.*FAI*YH/PI
       ELSE
         IF(ABS(FAI).GT. YEND) GOTO 22
         YLAT=LOG(TAN(.25*PI+0.5*FAI))*XH/PI
       ENDIF
       CALL ZPENUP(-XH,YLAT)
       CALL ZPENDN(XH,YLAT)
   22    CONTINUE
       RETURN
   34 CONTINUE
       MGR=(BETA*MG)/PI2
       FLONG=BETA/MGR
       IF(BETA.EQ.PI2) THEN
         ALST=-ALONS
       ELSE
         ALST=FANST
       ENDIF
       CALL ZPENUP( SIN(ALST)*AMP,-COS(ALST)*RC*AMP)
       DO 35 I=1,MGR
   35    CALL ZPENDN(AMP*SIN(I*FLONG+ALST),-AMP*COS(I*FLONG+ALST)*RC)
       RD=0.5*PI-RTOP
       RST=SIN(RD)*AMP*AMQ/(1.+(SWITCH-SVAGL*(1.-SWITCH))*COS(RD))
       DO 60 IM=0,NJ+NJ-1
       IF(IM.EQ.0) THEN
         RT=0.5*PI-RTOP
       ELSE
         RT=0.5*PI-(NJ-IM)*RDY
       ENDIF
       CSRT=COS(RT)
       RD=SIN(RT)*AMP*AMQ/(1.+(SWITCH-SVAGL*(1.-SWITCH))*CSRT)
       IF(RD.EQ.0.0) GOTO 60
       IF(CSRT.LE.CSWD) GOTO 60
       CALL ZPENUP( RD*SIN(ALST ),-RD*COS(ALST )*RC)
       DO 59 I=1,MGR
   59    CALL ZPENDN(SIN(I*FLONG+ALST)*RD,-COS(I*FLONG+ALST)*RD*RC)
   60    CONTINUE
       DO 61 IM=1,NM
       RSTEP=(IM-1)*RDX-ALONS
       IF(BETA.NE.PI2) THEN
         QSTEP=RSTEP-ALFA
         IF(QSTEP.GT. PI) QSTEP=MOD(QSTEP+PI,PI2)-PI
         IF(QSTEP.LE.-PI) QSTEP=MOD(QSTEP-PI,PI2)+PI
         IF(ABS(QSTEP).GE.0.5*BETA) GOTO 61
       ENDIF
       CALL ZPENUP(RST*SIN(RSTEP),-RST*COS(RSTEP)*RC)
       CALL ZPENDN(AMP*SIN(RSTEP),-AMP*COS(RSTEP)*RC)
   61    CONTINUE
       IF(BETA.NE.PI2) THEN
         CALL ZPENUP(RST*SIN(FANST),-RST*COS(FANST)*RC)
         CALL ZPENDN(AMP*SIN(FANST),-AMP*COS(FANST)*RC)
         CALL ZPENUP(RST*SIN(FANED),-RST*COS(FANED)*RC)
         CALL ZPENDN(AMP*SIN(FANED),-AMP*COS(FANED)*RC)
       ENDIF
       RETURN
   56 CONTINUE
       CALL ZPENUP(AMP,0.)
       DO 57 I=1,MG
   57    CALL ZPENDN(AMP*COS(I*DLONG),AMP*SIN(I*DLONG))
       XST=MOD(CX+180.,DX)*PI/180.
       DO 101 I=-NM,NM
       X=I*DX*PI/180.+XST
       IF(ABS(X).GE.0.5*PI) GOTO 101
       ASW=COS(X)*SWITCH
       RCS=AMP/(1.+COS(RTOP)*ASW)
       RSINM=SIN(X)
       CALL ZPENUP(COS(RTOP)*RSINM*RCS,SIN(RTOP)*RCS)
       DO 2 J=-JG,JG
       ALATJ=-J*DLAT
       RCS=AMP/(1.+COS(ALATJ)*ASW)
    2    CALL ZPENDN(COS(ALATJ)*RSINM*RCS,SIN(ALATJ)*RCS)
  101    CONTINUE
       DO 3 I=-NJ,NJ
       RSTEP=-I*RDY
       IF(I.EQ.-NJ) RSTEP=RTOP
       IF(I.EQ. NJ) RSTEP=-RTOP
       CSFAI= COS(RSTEP)
       SIFAI= SIN(RSTEP)
       IF(CSFAI.EQ.0.0) GOTO 3
       CALL ZPENUP(-CSFAI*AMP,SIFAI*AMP)
       DO 4 J=2,MGHP
       RCS=AMP/(1.+CSFAI*SIN((J-1)*DLONG)*SWITCH)
    4    CALL ZPENDN(-CSFAI*COS((J-1)*DLONG)*RCS,SIFAI*RCS)
    3    CONTINUE
       RETURN
   78 CONTINUE
       CALL ZPENUP(AMP,0.)
       DO 79 I=1,MG
   79    CALL ZPENDN(AMP*COS(DLONG*I),AMP*SIN(DLONG*I))
       DO 70 I=-NJ,NJ
       IF(I.EQ.NJ.OR.I.EQ.-NJ) THEN
         FAI=RTOP*(-I)/ABS(I)
       ELSE
         FAI=( -I )*RDY
       ENDIF
       IF(ABS(FAI).EQ.0.5*PI) GOTO 70
       DO 69 J=1,MGP
       ALONG=(J-1.)*DLONG
       IF(J.EQ.1) THEN
         IB=0
       ELSE
         IB=1
       ENDIF
   69    CALL ZPROJC(ALONG,FAI,IB,IA)
   70    CONTINUE
       DO 73 I=1,NM
       ALONG=(I-1.)*RDX
       DO 73 J=1,JG2P
       FAI=RTOP-(J-1.)*DLAT
       IF(J.EQ.1) THEN
         IB=0
       ELSE
         IB=1
       ENDIF
       CALL ZPROJC(ALONG,FAI,IB,IA)
   73    CONTINUE
       IF(AMR.EQ.0..OR.AMR.EQ.1.) RETURN
       RST=AMP*AMR
       CALL ZPENUP(RST,0.0)
       DO 74 I=1,MG
   74    CALLZPENDN(RST*COS(I*DLONG),RST*SIN(I*DLONG))
      RETURN
   80 CONTINUE
      CALL ZPENUP(2.*ARM,0.)
      DO 81 I=1,MG
   81 CALL ZPENDN(2.*ARM*COS(I*DLONG),ARM*SIN(I*DLONG))
      DO 85 I=-NJ1,NJ1
      YLAT=-I*RDY
      X1=-1.*PI
      X2= 1.*PI
      CALL XSINX(YLAT,XAN,PI)
      CALL ZPENUP(-2.*ARM*COS(XAN),ARM*SIN(XAN))
      CALL ZPENDN( 2.*ARM*COS(XAN),ARM*SIN(XAN))
85    CONTINUE
      CALL ZPENUP(0.,-ARM)
      CALL ZPENDN(0.,ARM)
       DO 113 J=1,NM/2
       X=ARM*J*DX/180.
       CALL ZPENUP(2.*X,0.)
       DO 112 I=1,MG
 112   CALL ZPENDN(2.*X*COS(I*DLONG),ARM*SIN(I*DLONG))
 113   CONTINUE
      END
