      SUBROUTINE INISET_lib(SQ,RSQ,NN,MM,NWJ2,MOCT)
      IMPLICIT NONE
      INTEGER NN,MM,NWJ2,MOCT
      REAL SQ(*),RSQ(*)
C
C     SETS UP ALL FIXED VALUES AND SET NAMELIST VARIABLES TO THEIR
C        DEFAULT SETTINGS
C
      INTEGER NWJCH,MP,JP,NP,NNP
C
      NNP=NN+1
C
C     NOW PERFORM CHECKS  AND SETUP ARRAYS
C
      NWJCH=0
      DO 10 MP=1,MM,MOCT
      DO 10 JP=MP,NN,2
10    NWJCH=NWJCH+1
      IF(NWJCH.NE.NWJ2)THEN
         PRINT*,' ABORT: NWJ2 IS NOT CORRECTLY SET '
         PRINT*,' IT SHOULD BE ',NWJCH,' BUT IS SPECIFIED AS ',NWJ2
         STOP
      ENDIF
      DO 20 NP=1,NNP
      SQ(NP)=NP*(NP-1)
      IF(NP.EQ.1)THEN
         RSQ(NP)=1.
      ELSE
         RSQ(NP)=1./SQ(NP)
      ENDIF
20    CONTINUE
      RETURN
      END
c
      SUBROUTINE INISET8(SQ,RSQ,NN,MM,NWJ2,MOCT)
      IMPLICIT NONE
      INTEGER NN,MM,NWJ2,MOCT
      REAL*8 SQ(*),RSQ(*)
C
C     SETS UP ALL FIXED VALUES AND SET NAMELIST VARIABLES TO THEIR
C        DEFAULT SETTINGS
C
      INTEGER NWJCH,MP,JP,NP,NNP
C
      NNP=NN+1
C
C     NOW PERFORM CHECKS  AND SETUP ARRAYS
C
      NWJCH=0
      DO 10 MP=1,MM,MOCT
      DO 10 JP=MP,NN,2
10    NWJCH=NWJCH+1
      IF(NWJCH.NE.NWJ2)THEN
         PRINT*,' ABORT: NWJ2 IS NOT CORRECTLY SET '
         PRINT*,' IT SHOULD BE ',NWJCH,' BUT IS SPECIFIED AS ',NWJ2
         STOP
      ENDIF
      DO 20 NP=1,NNP
      SQ(NP)=NP*(NP-1)
      IF(NP.EQ.1)THEN
         RSQ(NP)=1.
      ELSE
         RSQ(NP)=1./SQ(NP)
      ENDIF
20    CONTINUE
      RETURN
      END
